### ISSUE TITLE
Add function to set authorized issuers

### ISSUE THREAD

**Issue by juanmagiraldor** [kommitters/chaincerts-smart-contracts#167]
## Objective
We need to allow the authorization and revocation of multiple issuers simultaneously in the Vault contract. This will be achieved via a `authorize_issuers` function.

## Checklist

- [ ] Update the `authorize_issuer` to authorize an issuer.
- [ ] Update the `revoke_issuer` to remove an issuer.
- [ ] Create a new function `authorize_issuers` that should receive the list of addresses representing the authorized issuers.
- [ ] Update documentation.

**Comment by miguelnietoa** [comment]
Released in [v0.15.0](https://github.com/kommitters/chaincerts-smart-contracts/releases/tag/v0.15.0)
