### ISSUE TITLE
Implement new `register_vault`

### ISSUE THREAD

**Issue by juanmagiraldor** [kommitters/chaincerts-smart-contracts#168]
## Objective
Rename the `register_vault` to `register_vault_with_did` and implement a new `register_vault` function to deploy a [DID Contract](https://github.com/kommitters/soroban-did-contract), and register the new DID in a vault.

## Checklist
- [x] Rename `register_vault` to `register_vault_with_did`.
- [x] Implement `register_vault` function to deploy DID and register it in a vault:
  - [x] Create DID.
  - [x] Add the DID to the vault.
- [x] Update the documentation.

**Comment by miguelnietoa** [comment]
Released in [v0.15.0](https://github.com/kommitters/chaincerts-smart-contracts/releases/tag/v0.15.0)
